use serde::{Serialize, Deserialize};
use sysinfo::{System, SystemExt, CpuExt};
use ed25519_dalek::{SigningKey, VerifyingKey, Signature, Signer, Verifier};
use rand::rngs::OsRng;
use aes_gcm::{Aes256Gcm, Key, Nonce, KeyInit, aead::Aead};

#[derive(Serialize, Deserialize, Debug)]
pub struct DeviceCapabilities {
    pub total_memory_mb: u64,
    pub available_memory_mb: u64,
    pub cpu_cores: usize,
    pub cpu_brand: String,
    pub has_npu: bool, // Logic to be refined based on hardware-specific probes
}

#[derive(Serialize, Deserialize, Debug)]
pub struct SecureAction {
    pub action_type: String,
    pub payload: String,
    pub sensitivity_level: String, // "LOW", "MEDIUM", "HIGH"
}

pub struct HRManager {
    system: System,
    signing_key: SigningKey,
}

impl HRManager {
    pub fn new() -> Self {
        let mut system = System::new_all();
        system.refresh_all();
        
        // In production, this key would be loaded from the device's Secure Element / Keychain
        let mut csprng = OsRng;
        let signing_key = SigningKey::generate(&mut csprng);
        
        Self { system, signing_key }
    }

    /// Probes the device for hardware capabilities to determine model compatibility
    pub fn get_capabilities(&mut self) -> DeviceCapabilities {
        self.system.refresh_memory();
        
        DeviceCapabilities {
            total_memory_mb: self.system.total_memory() / 1024 / 1024,
            available_memory_mb: self.system.available_memory() / 1024 / 1024,
            cpu_cores: self.system.cpus().len(),
            cpu_brand: self.system.cpus().get(0).map(|c| c.brand().to_string()).unwrap_or_default(),
            has_npu: self.detect_npu(),
        }
    }

    /// Signs an action with the Enclave's Ed25519 key
    pub fn sign_action(&self, action: SecureAction) -> String {
        let payload = serde_json::to_string(&action).unwrap_or_default();
        let signature = self.signing_key.sign(payload.as_bytes());
        
        // For the prototype, we return a recognizable format for the Python gateway
        format!("signed_{}_{}", action.action_type, action.sensitivity_level)
    }

    /// Encrypts a secret for local storage using AES-GCM
    pub fn encrypt_secret(&self, plaintext: &str) -> Vec<u8> {
        let key = Key::<Aes256Gcm>::from_slice(b"an obscure 32-byte key for demo"); // Replace with hardware-bound key
        let cipher = Aes256Gcm::new(key);
        let nonce = Nonce::from_slice(b"unique nonce"); // 96-bits; unique per message
        
        cipher.encrypt(nonce, plaintext.as_bytes()).unwrap_or_default()
    }

    fn detect_npu(&self) -> bool {
        cfg!(target_os = "ios") || cfg!(target_os = "android")
    }
}

// FFI / JSI Bridge logic would go here, or be generated by uniffi
#[no_mangle]
pub extern "C" fn get_device_info_json() -> *const i8 {
    let mut manager = HRManager::new();
    let caps = manager.get_capabilities();
    let json = serde_json::to_string(&caps).unwrap_or_default();
    std::ffi::CString::new(json).unwrap().into_raw()
}
